"""Auto-generated by Detective — warrant-classed tests for Wesker/session_manifest.py::_digest.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.session_manifest import _digest


@pytest.mark.detective
def test__digest_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _digest(path="")
    assert result == ""
