"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::should_recycle.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import should_recycle


@pytest.mark.detective
def test_should_recycle_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = should_recycle(evaluated=1, max_per_worker=2)
    assert result is False


@pytest.mark.detective
def test_should_recycle_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = should_recycle(evaluated=0, max_per_worker=0)
    assert result is False


@pytest.mark.detective
def test_should_recycle_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = should_recycle(evaluated=-1, max_per_worker=-1)
    assert result is False


@pytest.mark.detective
def test_should_recycle_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = should_recycle(evaluated=1, max_per_worker=1)
    assert result is True


@pytest.mark.detective
def test_should_recycle_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = should_recycle(evaluated=2, max_per_worker=1)
    assert result is True
