# detective-content-sha256: 9f9e0f45207041f05f0246ee32c8bbb1e7d268a4633a5472baddce4d036d7c78
"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::describe_truncation.
Function digest: b8372515db83879f.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Wesker.ci import describe_truncation


@pytest.mark.detective
def test_describe_truncation_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = describe_truncation(truncated=[{}], limit=1)
    assert (
        result
        == "Cut, cause not recorded: none. [1]\n  ? — 0.0 s, 0/0 mutants evaluated"
    )
