# detective-content-sha256: 59384862603ffadbf5c3781774284772c9a2cb7f2a8585b77229d3f2da8938c1
"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::form_b_equivalence.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import form_b_equivalence


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["match", "match"],), "equivalent"),
        ((["match", "differ"],), "distinguished"),
        ((["raised"],), "no_evidence"),
    ],
)
def test_form_b_equivalence_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert form_b_equivalence(*args) == expected
