"""Auto-generated by Detective — warrant-classed tests for Wesker/trace_cache.py::replayed_negative_admission.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.trace_cache import replayed_negative_admission


@pytest.mark.detective
def test_replayed_negative_admission_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = replayed_negative_admission(
        has_outcome=True, fingerprint_matches=True, is_property_test=True
    )
    assert result == "unknown"


@pytest.mark.detective
def test_replayed_negative_admission_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = replayed_negative_admission(
        has_outcome=False, fingerprint_matches=True, is_property_test=False
    )
    assert result == "unknown"


@pytest.mark.detective
def test_replayed_negative_admission_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = replayed_negative_admission(
        has_outcome=True, fingerprint_matches=False, is_property_test=False
    )
    assert result == "unknown"


@pytest.mark.detective
def test_replayed_negative_admission_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = replayed_negative_admission(
        has_outcome=True, fingerprint_matches=True, is_property_test=False
    )
    assert result == "not_reached"
