"""Auto-generated by Detective — warrant-classed tests for Wesker/subsumption.py::distinct_obligations.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.subsumption import distinct_obligations


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"survivor": [], "A": ["t1"], "B": ["t1"]}, 3), 4),
        (({"x": ["x"]}, 1), 2),
    ],
)
def test_distinct_obligations_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert distinct_obligations(*args) == expected
