"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::entry_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import entry_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((0, False), "unobserved"),
        ((1, True), "entered"),
        ((1, False), "not_entered"),
    ],
)
def test_entry_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert entry_disposition(*args) == expected


@pytest.mark.detective
def test_entry_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = entry_disposition(ran=-1, entered=False)
    assert result == "unobserved"
