# detective-content-sha256: 9e55335554dedfd304f03152b9713a80cce37ec5f72bbb0909f323b78c8bae9b
"""Auto-generated by Detective — warrant-classed tests for Wesker/swap_plan.py::swap_pairs.
Function digest: 545fa0366b943932.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.swap_plan import swap_pairs


@pytest.mark.detective
def test_swap_pairs_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = swap_pairs(n_positional=1)
    assert result == []


@pytest.mark.detective
def test_swap_pairs_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = swap_pairs(n_positional=2)
    assert result == [(0, 1)]
