"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_adaptive_allowance.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import _adaptive_allowance


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((2.0, 5000.0, 5000.0), 100.0),
        ((2.0, 5000.0, 30.0), 30.0),
        ((None, 5000.0, 5000.0), 5000.0),
    ],
)
def test__adaptive_allowance_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _adaptive_allowance(*args) == expected
