"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::baseline_probe_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import baseline_probe_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), "inert"),
        ((None,), "usable"),
        (("assertion",), "inert"),
        (("exception",), "inert"),
        (("crash",), "inert"),
        (("timeout",), "inert"),
        (("",), "inert"),
    ],
)
def test_baseline_probe_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert baseline_probe_disposition(*args) == expected


@pytest.mark.detective
def test_baseline_probe_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = baseline_probe_disposition(outcome="uncontained")
    assert result == "uncontained"
