"""Auto-generated by Detective — warrant-classed tests for Wesker/line_coverage.py::admissible_coverage.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.line_coverage import admissible_coverage


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"x": [1]}, ["x"]), {}),
        (({"x": [1]}, ["x", "x"]), {}),
    ],
)
def test_admissible_coverage_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert admissible_coverage(*args) == expected


@pytest.mark.detective
def test_admissible_coverage_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = admissible_coverage(observed={"x": [1]}, inadmissible=[])
    assert result == {"x": [1]}
