"""Auto-generated by Detective — warrant-classed tests for Wesker/memory_guard.py::memory_budget_standing.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.memory_guard import memory_budget_standing


@pytest.mark.detective
def test_memory_budget_standing_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = memory_budget_standing(growth_bytes=1, budget_bytes=2, capability="abc")
    assert result == "within"


@pytest.mark.detective
def test_memory_budget_standing_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = memory_budget_standing(
        growth_bytes=-1, budget_bytes=-1, capability="unavailable"
    )
    assert result == "unmeasurable"


@pytest.mark.detective
def test_memory_budget_standing_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = memory_budget_standing(growth_bytes=2, budget_bytes=-1, capability="abc")
    assert result == "within"


@pytest.mark.detective
def test_memory_budget_standing_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = memory_budget_standing(growth_bytes=1, budget_bytes=1, capability="x")
    assert result == "within"
