# detective-content-sha256: 528fefbb99d79d3d8393cf7d8b690a62a1400cbdfc99f28fd62c97bbae153722
"""Auto-generated by Detective — warrant-classed tests for Wesker/monitoring.py::step_budget_verdict.
Function digest: d8eca6039415c200.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Wesker.monitoring import step_budget_verdict


@pytest.mark.detective
def test_step_budget_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = step_budget_verdict(iterations=1, cap=2)
    assert result == "within"
