"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::mutant_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import mutant_verdict


@pytest.mark.detective
def test_mutant_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = mutant_verdict(outcome="abc")
    assert result == "harness"


@pytest.mark.detective
def test_mutant_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_verdict(outcome="failed")
    assert result == "killed"


@pytest.mark.detective
def test_mutant_verdict_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_verdict(outcome="passed")
    assert result == "survived"


@pytest.mark.detective
def test_mutant_verdict_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_verdict(outcome="timeout")
    assert result == "killed"
