# detective-content-sha256: 031621aa248f827762a0712e81d27beaefabe27aafadf43d3a841ab8220226ee
"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::execution_lock_disposition.
Function digest: 8f0703283b596e96.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import execution_lock_disposition


@pytest.mark.detective
def test_execution_lock_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = execution_lock_disposition(
        acquired=True, owner_tid=1, self_tid=2, live_tids=(1,)
    )
    assert result == "acquired"


@pytest.mark.detective
def test_execution_lock_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = execution_lock_disposition(
        acquired=False, owner_tid=-1, self_tid=-1, live_tids=(1,)
    )
    assert result == "orphaned"


@pytest.mark.detective
def test_execution_lock_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = execution_lock_disposition(
        acquired=False, owner_tid=1, self_tid=3, live_tids=(1,)
    )
    assert result == "held_by_live_thread"


@pytest.mark.detective
def test_execution_lock_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = execution_lock_disposition(
        acquired=False, owner_tid=0, self_tid=1, live_tids=(1,)
    )
    assert result == "orphaned"


@pytest.mark.detective
def test_execution_lock_disposition_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = execution_lock_disposition(
        acquired=False, owner_tid=0, self_tid=2, live_tids=(1,)
    )
    assert result == "free_but_unacquired"
