"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::fast_mode_standing.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import fast_mode_standing


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((False, False, False, False, False), "hermetic"),
        ((True, False, False, False, False), "refuse_subprocess"),
        ((False, True, False, False, False), "refuse_thread"),
        ((False, False, True, False, False), "refuse_collector"),
        ((False, False, False, True, False), "refuse_signal"),
        ((False, False, False, False, True), "refuse_fixture"),
    ],
)
def test_fast_mode_standing_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert fast_mode_standing(*args) == expected
