"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::aggregate_kill_reason.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import aggregate_kill_reason


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["x"],), ""),
        ((["assertion"],), "assertion"),
        ((["exception"],), "exception"),
        ((["crash"],), "crash"),
    ],
)
def test_aggregate_kill_reason_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert aggregate_kill_reason(*args) == expected
