# detective-content-sha256: e725e53a59924b20e50d593030e4257e7ce999ce96973e98178e2d2f891945a0
"""Auto-generated by Detective — warrant-classed tests for Wesker/swap_plan.py::swap_label.
Function digest: a4e1a445376e3f60.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.swap_plan import swap_label


@pytest.mark.detective
def test_swap_label_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = swap_label(callee="abc", i=1, j=2)
    assert result == "SWAP:abc~p1"


@pytest.mark.detective
def test_swap_label_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = swap_label(callee="", i=0, j=-1)
    assert result == "SWAP:~p0,-1"


@pytest.mark.detective
def test_swap_label_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = swap_label(callee="", i=0, j=1)
    assert result == "SWAP:"
