"""Auto-generated by Detective — warrant-classed tests for Wesker/filter.py::operator_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.filter import operator_disposition


@pytest.mark.detective
def test_operator_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = operator_disposition(generated=1, withheld=2)
    assert result == "generated"


@pytest.mark.detective
def test_operator_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = operator_disposition(generated=0, withheld=-1)
    assert result == "not_applicable"


@pytest.mark.detective
def test_operator_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = operator_disposition(generated=-1, withheld=-1)
    assert result == "not_applicable"


@pytest.mark.detective
def test_operator_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = operator_disposition(generated=-1, withheld=0)
    assert result == "not_applicable"


@pytest.mark.detective
def test_operator_disposition_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = operator_disposition(generated=-1, withheld=1)
    assert result == "withheld"
