"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::resolve_test_id.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import resolve_test_id


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            (
                "tests/test_x.py::test_f[case0]",
                "test_f",
                "/abs/tests/test_x.py",
                "/abs",
                "case0",
            ),
            "tests/test_x.py::test_f[case0]",
        ),
        (("abc", "abc", "abc", "abc", "abc"), "legacy:.::abc[abc]"),
        (
            ("test_shared", "test_shared", "/root/tests/test_other.py", "/root", ""),
            "legacy:tests/test_other.py::test_shared",
        ),
        (
            ("_heavy.<locals>.t", "heavy_1", "/root/tests/test_b.py", "/root", ""),
            "legacy:tests/test_b.py::_heavy.<locals>.t#heavy_1",
        ),
        (
            ("test_x", "test_x", "/other/tests/test_x.py", "/root", ""),
            "legacy:../other/tests/test_x.py::test_x",
        ),
        (
            (
                "test_mod.<locals>.test_shared",
                "test_shared",
                "/root/tests/test_other.py",
                "/root",
                "",
            ),
            "legacy:tests/test_other.py::test_mod.<locals>.test_shared",
        ),
    ],
)
def test_resolve_test_id_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert resolve_test_id(*args) == expected


@pytest.mark.detective
def test_resolve_test_id_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = resolve_test_id(
        node_id="test_refreshing_one_file_keeps_a_same_named_test_in_another_module.<locals>.test_shared",
        display_name="test_shared",
        origin="/private/var/folders/y3/9hy3l65d7xvdl89kh19dnlf40000gp/T/pytest-of-rohanvinaik/pytest-1106/test_refreshing_one_file_keeps83/test_other.py",
        project_root=".",
        case="",
    )
    assert (
        result
        == "legacy:../../../../private/var/folders/y3/9hy3l65d7xvdl89kh19dnlf40000gp/T/pytest-of-rohanvinaik/pytest-1106/test_refreshing_one_file_keeps83/test_other.py::test_refreshing_one_file_keeps_a_same_named_test_in_another_module.<locals>.test_shared"
    )


@pytest.mark.detective
def test_resolve_test_id_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = resolve_test_id(
        node_id="a", display_name="abc", origin="", project_root="a", case="abc"
    )
    assert result == "legacy:?::a#abc[abc]"


@pytest.mark.detective
def test_resolve_test_id_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = resolve_test_id(
        node_id="test_refreshing_one_file_keeps_a_same_named_test_in_another_module.<locals>.test_shared",
        display_name="test_shared",
        origin="/private/var/folders/y3/9hy3l65d7xvdl89kh19dnlf40000gp/T/pytest-of-rohanvinaik/pytest-1107/test_refreshing_one_file_keeps55/test_other.py",
        project_root=".",
        case="",
    )
    assert (
        result
        == "legacy:../../../../private/var/folders/y3/9hy3l65d7xvdl89kh19dnlf40000gp/T/pytest-of-rohanvinaik/pytest-1107/test_refreshing_one_file_keeps55/test_other.py::test_refreshing_one_file_keeps_a_same_named_test_in_another_module.<locals>.test_shared"
    )


@pytest.mark.detective
def test_resolve_test_id_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = resolve_test_id(
        node_id="test_refreshing_one_file_keeps_a_same_named_test_in_another_module.<locals>.test_shared",
        display_name="test_shared",
        origin="/private/var/folders/y3/9hy3l65d7xvdl89kh19dnlf40000gp/T/pytest-of-rohanvinaik/pytest-1108/test_refreshing_one_file_keeps55/test_other.py",
        project_root=".",
        case="",
    )
    assert (
        result
        == "legacy:../../../../private/var/folders/y3/9hy3l65d7xvdl89kh19dnlf40000gp/T/pytest-of-rohanvinaik/pytest-1108/test_refreshing_one_file_keeps55/test_other.py::test_refreshing_one_file_keeps_a_same_named_test_in_another_module.<locals>.test_shared"
    )
