"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::route_admits.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import route_admits


@pytest.mark.detective
def test_route_admits_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = route_admits(code="", conservative=False)
    assert result is True


@pytest.mark.detective
def test_route_admits_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = route_admits(code="impossible_observed", conservative=False)
    assert result is False
