# detective-content-sha256: 8c8d9aeb865f847eae5e93365830d69bb68114ed102aa5f4b4660adfbddf0d79
"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::parse_lock_owner.
Function digest: ca3cd6d3a78aea31.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import parse_lock_owner


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("<locked _thread.RLock object owner=6147403776 count=1 at 0x1049c9090>",),
            6147403776,
        ),
        (("owner=",), 0),
        (("nothing here",), 0),
    ],
)
def test_parse_lock_owner_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert parse_lock_owner(*args) == expected
