"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::isolated_test_outcome.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import isolated_test_outcome


@pytest.mark.detective
def test_isolated_test_outcome_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = isolated_test_outcome(returncode=1, timed_out=True)
    assert result == "timeout"


@pytest.mark.detective
def test_isolated_test_outcome_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = isolated_test_outcome(returncode=0, timed_out=False)
    assert result == "passed"


@pytest.mark.detective
def test_isolated_test_outcome_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = isolated_test_outcome(returncode=1, timed_out=False)
    assert result == "failed"


@pytest.mark.detective
def test_isolated_test_outcome_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = isolated_test_outcome(returncode=5, timed_out=False)
    assert result == "no_tests"


@pytest.mark.detective
def test_isolated_test_outcome_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = isolated_test_outcome(returncode=-1, timed_out=False)
    assert result == "error"
