"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::callable_test_id.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import callable_test_id


@pytest.mark.detective
def test_callable_test_id_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = callable_test_id(call=1, project_root="abc")
    assert result == "legacy:?::unknown"


@pytest.mark.detective
def test_callable_test_id_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = callable_test_id(call=-1, project_root="")
    assert result == "legacy:?::unknown"
