"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::baseline_determinism.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import baseline_determinism


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([1, 2, 3], "passed", [1, 2, 3], "passed"), "deterministic"),
        (([1, 2], "passed", [1, 2], "failed"), "nondeterministic"),
        (([1, 2], "passed", [1, 2, 3], "passed"), "nondeterministic"),
    ],
)
def test_baseline_determinism_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert baseline_determinism(*args) == expected
