"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::_is_test_filename.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import _is_test_filename


@pytest.mark.detective
def test__is_test_filename_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _is_test_filename(basename="abc", patterns=("x",))
    assert result is False


@pytest.mark.detective
def test__is_test_filename_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _is_test_filename(
        basename="app_test.py", patterns=("test_*.py", "*_test.py")
    )
    assert result is True
