"""Auto-generated by Detective — warrant-classed tests for Wesker/filter.py::_census_row.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.filter import _census_row


@pytest.mark.detective
def test__census_row_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _census_row(3, 2)
    assert result == {"generated": 3, "withheld": 2, "disposition": "generated"}
