# detective-content-sha256: fef74c9daded36b02d6032f1e5f2856964718515790d18bf33beac98bdb1f199
"""Auto-generated by Detective — warrant-classed tests for Wesker/trace_evidence.py::baseline_outcome.
Function digest: 28d9a5d957d25eac.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Wesker.trace_evidence import baseline_outcome


@pytest.mark.detective
def test_baseline_outcome_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = baseline_outcome(run_code="abc", item_status="abc")
    assert result == "error"
