"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::classify_kill_reason.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import classify_kill_reason


@pytest.mark.detective
def test_classify_kill_reason_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_kill_reason(is_assertion=True, is_declared_failure=True)
    assert result == "assertion"


@pytest.mark.detective
def test_classify_kill_reason_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_kill_reason(is_assertion=False, is_declared_failure=True)
    assert result == "exception"


@pytest.mark.detective
def test_classify_kill_reason_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_kill_reason(is_assertion=False, is_declared_failure=False)
    assert result == "crash"
