"""Auto-generated by Detective — warrant-classed tests for Wesker/subsumption.py::redundancy_groups.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.subsumption import redundancy_groups


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"x": ["x"]},), [["x"]]),
        (
            ({"survivor": [], "A": ["t1", "t2"], "B": ["t2", "t1"], "C": ["t1"]},),
            [["A", "B"], ["C"]],
        ),
    ],
)
def test_redundancy_groups_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert redundancy_groups(*args) == expected
