"""Auto-generated by Detective — warrant-classed tests for Wesker/session_manifest.py::collection_identity_standing.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.session_manifest import collection_identity_standing


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, ("x",)), "ambiguous"),
        ((True, ()), "confirmed"),
        ((False, ("pkg.mod",)), "unobserved"),
    ],
)
def test_collection_identity_standing_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert collection_identity_standing(*args) == expected
