"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_baseline_failures.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import _baseline_failures


@pytest.mark.detective
def test__baseline_failures_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _baseline_failures(
        test_functions=[None], original_func=1, qualname="abc", timeout_ms=1.0625
    )
    assert result == (set(), False)


@pytest.mark.detective
def test__baseline_failures_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _baseline_failures(
        test_functions=[None], original_func=-1, qualname="", timeout_ms=-1.0
    )
    assert result == (set(), False)
