"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::_impact_lookup_keys.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import _impact_lookup_keys


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), ("abc",)),
        (("Basket.tier",), ("Basket.tier", "tier")),
        (("a.b.c",), ("a.b.c", "c")),
    ],
)
def test__impact_lookup_keys_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _impact_lookup_keys(*args) == expected
