"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::mutant_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import mutant_disposition


@pytest.mark.detective
def test_mutant_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = mutant_disposition(
        constructed=True, installed=True, entered=True, contained=True, killed=True
    )
    assert result == "killed_after_entry"


@pytest.mark.detective
def test_mutant_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_disposition(
        constructed=True, installed=True, entered=False, contained=False, killed=False
    )
    assert result == "not_entered"


@pytest.mark.detective
def test_mutant_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_disposition(
        constructed=False, installed=False, entered=False, contained=False, killed=False
    )
    assert result == "harness_error"


@pytest.mark.detective
def test_mutant_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_disposition(
        constructed=True, installed=False, entered=False, contained=False, killed=False
    )
    assert result == "not_installed"


@pytest.mark.detective
def test_mutant_disposition_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_disposition(
        constructed=True, installed=True, entered=True, contained=False, killed=False
    )
    assert result == "cut"


@pytest.mark.detective
def test_mutant_disposition_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutant_disposition(
        constructed=True, installed=True, entered=True, contained=True, killed=False
    )
    assert result == "survived_after_entry"
