"""Auto-generated by Detective — warrant-classed tests for Wesker/line_coverage.py::trace_evidence_admissible.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.line_coverage import trace_evidence_admissible


@pytest.mark.detective
def test_trace_evidence_admissible_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = trace_evidence_admissible(
        baseline_outcome="abc", truncated=True, contained=True
    )
    assert result == (False, "truncated")


@pytest.mark.detective
def test_trace_evidence_admissible_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = trace_evidence_admissible(
        baseline_outcome="passed", truncated=False, contained=True
    )
    assert result == (True, "")


@pytest.mark.detective
def test_trace_evidence_admissible_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = trace_evidence_admissible(
        baseline_outcome="", truncated=False, contained=True
    )
    assert result == (False, "baseline_")


@pytest.mark.detective
def test_trace_evidence_admissible_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = trace_evidence_admissible(
        baseline_outcome="passed", truncated=False, contained=False
    )
    assert result == (False, "uncontained")
