"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::scope_fast_mode_standing.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import scope_fast_mode_standing


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["hermetic", "refuse_subprocess"],), "refuse_subprocess"),
        ((["hermetic", "hermetic"],), "hermetic"),
    ],
)
def test_scope_fast_mode_standing_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert scope_fast_mode_standing(*args) == expected
