"""Auto-generated by Detective — warrant-classed tests for Wesker/session_manifest.py::conflicting_module_names.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.session_manifest import conflicting_module_names


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"pkg.mod": ("/a/mod.py", "/b/mod.py")},), ("pkg.mod",)),
        (({"pkg.mod": ("/a/mod.py",)},), ()),
        (({"pkg.mod": ("/a/mod.py", "/a/mod.py")},), ()),
        (({"pkg.mod": ()},), ()),
        (({},), ()),
        (
            ({"good": ("/a.py",), "bad": ("/b.py", "/c.py"), "also": ("/d.py",)},),
            ("bad",),
        ),
        (({"z": ("/1.py", "/2.py"), "a": ("/3.py", "/4.py")},), ("a", "z")),
        (({"x": ("x",)},), ()),
    ],
)
def test_conflicting_module_names_golden(args, expected):
    """VALUE golden captures — pure + deterministic (8 inputs)."""
    assert conflicting_module_names(*args) == expected
