"""Auto-generated by Detective — warrant-classed tests for Wesker/session_manifest.py::manifest_admissibility.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.session_manifest import manifest_admissibility


@pytest.mark.detective
def test_manifest_admissibility_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = manifest_admissibility(manifest_scope=1, current_scope=2)
    assert result == "refuse"


@pytest.mark.detective
def test_manifest_admissibility_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = manifest_admissibility(manifest_scope=1, current_scope=1)
    assert result == "admit"


@pytest.mark.detective
def test_manifest_admissibility_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = manifest_admissibility(manifest_scope=-1, current_scope=-1)
    assert result == "refuse"


@pytest.mark.detective
def test_manifest_admissibility_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = manifest_admissibility(manifest_scope=-1, current_scope=1)
    assert result == "refuse"
