# detective-content-sha256: f3b7e80f3a9ed8585dbb5327129a3e40e5f51a8eb488939f292034706b409625
"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::_describe_containment_lost.
Function digest: 94070dfc7a7b802e.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Wesker.ci import _describe_containment_lost


@pytest.mark.detective
def test__describe_containment_lost_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = _describe_containment_lost(lost=[{}], limit=1)
    assert result == ["    could not stop: an unnamed test, running mutant ? (line ?)"]
