# detective-content-sha256: 991aa2b3d67889a82f6a1a6ed425b4ece7d983617b624fabe81e7ad8fdfd856a
"""Auto-generated by Detective — warrant-classed tests for Wesker/action.py::gate_truncation.
Function digest: 14d312fb0786a0d8.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Wesker.action import gate_truncation


@pytest.mark.detective
def test_gate_truncation_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = gate_truncation(report={"total_truncated": 3})
    assert (
        result
        == "3 function(s) were only PARTIALLY evaluated.\nTheir unevaluated mutants are missing from both sides of the ratio, so this is a sample, not a completeness measurement.\nRaise `budget` (or set [tool.wesker] max_per_category); an uncontained worker needs the target's blocking call bounded or run in a killable process."
    )


@pytest.mark.detective
def test_gate_truncation_value_1():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = gate_truncation(report={})
    assert result is None
