"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::merge_unscored.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.engine import merge_unscored


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([{"x": 1}],), (1, {"x": 1})),
        (([{"x": 1}, {"x": 1}],), (2, {"x": 2})),
    ],
)
def test_merge_unscored_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert merge_unscored(*args) == expected
