# detective-content-sha256: 1737055518b9dcafa3ec64dcecb1c1b19b167ee51225b2ddf662cb9a270f7400
"""Auto-generated by Detective — warrant-classed tests for Wesker/policy.py::_fingerprint_counts.
Function digest: c9f6a705ec9f2619.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.policy import _fingerprint_counts


@pytest.mark.detective
def test__fingerprint_counts_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _fingerprint_counts()
    assert result == {
        "fp_value": {
            "VALUE": 9,
            "SWAP": 0,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 0,
            "LOGICAL": 0,
            "STMT": 1,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_boundary": {
            "VALUE": 0,
            "SWAP": 0,
            "STATE": 1,
            "BOUNDARY": 17,
            "TYPE": 0,
            "ARITHMETIC": 0,
            "LOGICAL": 0,
            "STMT": 0,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_arith_logic": {
            "VALUE": 2,
            "SWAP": 0,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 4,
            "LOGICAL": 2,
            "STMT": 1,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_bitwise": {
            "VALUE": 2,
            "SWAP": 0,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 8,
            "LOGICAL": 0,
            "STMT": 1,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_swap": {
            "VALUE": 4,
            "SWAP": 9,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 1,
            "LOGICAL": 0,
            "STMT": 0,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_state_type_exc": {
            "VALUE": 4,
            "SWAP": 4,
            "STATE": 6,
            "BOUNDARY": 3,
            "TYPE": 1,
            "ARITHMETIC": 1,
            "LOGICAL": 1,
            "STMT": 3,
            "EXCEPTION": 3,
            "DATAFLOW": 0,
        },
        "fp_stmt": {
            "VALUE": 7,
            "SWAP": 1,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 0,
            "LOGICAL": 0,
            "STMT": 3,
            "EXCEPTION": 0,
            "DATAFLOW": 2,
        },
        "fp_async": {
            "VALUE": 2,
            "SWAP": 0,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 1,
            "LOGICAL": 0,
            "STMT": 0,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_dataflow": {
            "VALUE": 0,
            "SWAP": 0,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 1,
            "LOGICAL": 0,
            "STMT": 0,
            "EXCEPTION": 0,
            "DATAFLOW": 2,
        },
        "fp_str_arith": {
            "VALUE": 9,
            "SWAP": 1,
            "STATE": 1,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 3,
            "LOGICAL": 0,
            "STMT": 0,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
        "fp_state_spellings": {
            "VALUE": 0,
            "SWAP": 0,
            "STATE": 5,
            "BOUNDARY": 0,
            "TYPE": 0,
            "ARITHMETIC": 1,
            "LOGICAL": 0,
            "STMT": 4,
            "EXCEPTION": 0,
            "DATAFLOW": 0,
        },
    }
