"""Auto-generated by Detective — warrant-classed tests for Wesker/memory_guard.py::memory_enforcement_standing.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.memory_guard import memory_enforcement_standing


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True,), "enforced"),
        ((False,), "telemetry_only"),
    ],
)
def test_memory_enforcement_standing_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert memory_enforcement_standing(*args) == expected
