"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::route_test_item.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import route_test_item


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, True, "abc", True), "candidate_static"),
        ((False, False, "unseen", True), "unknown_dynamic"),
    ],
)
def test_route_test_item_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert route_test_item(*args) == expected


@pytest.mark.detective
def test_route_test_item_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = route_test_item(
        names_target=False,
        fixture_reaches=False,
        observed_reach="reached",
        dynamic_uncertain=False,
    )
    assert result == "candidate_observed"


@pytest.mark.detective
def test_route_test_item_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = route_test_item(
        names_target=True,
        fixture_reaches=True,
        observed_reach="not_reached",
        dynamic_uncertain=True,
    )
    assert result == "impossible_observed"


@pytest.mark.detective
def test_route_test_item_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = route_test_item(
        names_target=False,
        fixture_reaches=True,
        observed_reach="",
        dynamic_uncertain=True,
    )
    assert result == "candidate_fixture"


@pytest.mark.detective
def test_route_test_item_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = route_test_item(
        names_target=False,
        fixture_reaches=False,
        observed_reach="abc",
        dynamic_uncertain=False,
    )
    assert result == "unknown_no_path"
