"""Auto-generated by Detective — warrant-classed tests for Wesker/tce.py::bytecode_equivalent.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.tce import bytecode_equivalent


@pytest.mark.detective
def test_bytecode_equivalent_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(original_src="abc", mutant_src="abc")
    assert result is True


@pytest.mark.detective
def test_bytecode_equivalent_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(
        original_src="def f():\n    return 1", mutant_src="def f():\n    return 2"
    )
    assert result is False


@pytest.mark.detective
def test_bytecode_equivalent_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = bytecode_equivalent(
        original_src="def f(): pass", mutant_src="def f(: pass"
    )
    assert result is False


@pytest.mark.detective
def test_bytecode_equivalent_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(original_src="x = 1 + 1", mutant_src="x = 2")
    assert result is True


@pytest.mark.detective
def test_bytecode_equivalent_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(original_src="x = 1000", mutant_src="x = 1001")
    assert result is False


@pytest.mark.detective
def test_bytecode_equivalent_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(original_src="x = 0", mutant_src="x = False")
    assert result is False


@pytest.mark.detective
def test_bytecode_equivalent_value_6():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(original_src="x = 1", mutant_src="x = 1.0")
    assert result is False


@pytest.mark.detective
def test_bytecode_equivalent_value_7():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bytecode_equivalent(
        original_src="def f():\n    return a", mutant_src="def f():\n    return b"
    )
    assert result is False
