# detective-content-sha256: eeadb9db5d1281ee34ffdd1f8fd34629bba0e92715842a42be30c9b7a0ec5af9
"""Auto-generated by Detective — warrant-classed tests for Wesker/monitoring.py::step_cap.
Function digest: dc7a6a6011901325.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Wesker.monitoring import step_cap


@pytest.mark.detective
def test_step_cap_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = step_cap(original_iterations=1, factor=2, floor=3)
    assert result == 5


@pytest.mark.detective
def test_step_cap_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = step_cap(original_iterations=-1, factor=-1, floor=-1)
    assert result == -1
