"""Auto-generated by Detective — warrant-classed tests for Wesker/isolation.py::hazards_from_names.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.isolation import hazards_from_names


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ([], False),
            ["signal_main_thread", "spawns_subprocess", "starts_background_thread"],
        ),
        ((["subprocess"], True), ["spawns_subprocess"]),
        ((["threading"], True), ["starts_background_thread"]),
        ((["signal"], True), ["signal_main_thread"]),
    ],
)
def test_hazards_from_names_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert hazards_from_names(*args) == expected
