# detective-content-sha256: 1e932f3e87610d3615d49e441ecd6cc0f36477a8a55a68763c414fa1fe88848b
"""Auto-generated by Detective — warrant-classed tests for Wesker/swap_plan.py::swap_plan.
Function digest: d15b60f8af8cfb83.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.swap_plan import swap_plan


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2), ([], 0)),
        ((2, 1), ([(0, 1)], 0)),
    ],
)
def test_swap_plan_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert swap_plan(*args) == expected


@pytest.mark.detective
def test_swap_plan_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = swap_plan(n_positional=2, budget=-1)
    assert result == ([], 1)


@pytest.mark.detective
def test_swap_plan_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = swap_plan(n_positional=3, budget=-1)
    assert result == ([], 3)
