"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::is_truncated_measurement.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Wesker.ci import is_truncated_measurement


@pytest.mark.detective
def test_is_truncated_measurement_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_truncated_measurement(coverage_depth="cut", budget_exhausted=False)
    assert result is True


@pytest.mark.detective
def test_is_truncated_measurement_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_truncated_measurement(coverage_depth="sampled", budget_exhausted=False)
    assert result is False
