"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::dimension_budget."""

import ast

import pytest

from Wesker.engine import dimension_budget


@pytest.mark.detective
def test_dimension_budget_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = dimension_budget(
        ast.parse("def _f(x):\n    return x").body[0], 1, {(1, 1)}
    )
    assert result == 0
