"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_outcome_on_original."""

import pytest

from Wesker.engine import _outcome_on_original


@pytest.mark.detective
def test__outcome_on_original_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _outcome_on_original(
        test_fn=1,
        original_func=1,
        module_saved=[(None, None)],
        func_name="abc",
        remaining_ms=1.0625,
    )
    assert result == "crash"
