"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::coverage_floor."""

import pytest

from Wesker.engine import coverage_floor


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (((100, 5), 2, 1), 0.6321205588285577),
        (((3, 4), 0, 1), 1.0),
        (((100,), 2, 2), 0.8646647167633873),
        (((), 0, 0), 1.0),
        (((1,), 1, -1), 0.0),
        (((0, 100), 2, 1), 0.6321205588285577),
        (((1,), 2, 0), 0.0),
        (((1,), 1, 2), 1.0),
    ],
)
def test_coverage_floor_golden(args, expected):
    """VALUE golden captures — pure + deterministic (8 inputs)."""
    assert coverage_floor(*args) == expected


@pytest.mark.detective
def test_coverage_floor_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = coverage_floor((1,), 2, 1)
    assert result == 1.0
