"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_statically_str."""

import ast

import pytest

from Wesker.engine import _statically_str


@pytest.mark.detective
def test__statically_str_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _statically_str(
        node=ast.parse(
            "def _f(x, y):\n    total = x + y\n    total = abs(total)\n    if total > 10:\n        raise ValueError('big')\n    return round(total, 2)"
        ).body[0]
    )
    assert result is False
