"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_count_dataflow_targets."""

import ast

import pytest

from Wesker.engine import _count_dataflow_targets


@pytest.mark.detective
def test__count_dataflow_targets_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _count_dataflow_targets(
        func_node=ast.parse(
            "def _f(x, y):\n    total = x + y\n    total = abs(total)\n    if total > 10:\n        raise ValueError('big')\n    return round(total, 2)"
        ).body[0],
        mode="abc",
    )
    assert result == 0
