"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_dataflow_candidates."""

import ast

import pytest

from Wesker.engine import _dataflow_candidates


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((ast.parse("def _f():\n    pass").body[0],), {}),
        (
            (
                ast.parse(
                    "def _f(x):\n    try:\n        return int(x)\n    except ValueError:\n        return 0"
                ).body[0],
            ),
            {},
        ),
        (
            (
                ast.parse(
                    "class C:\n    def _f(self, v):\n        self.v = v\n        return self.v"
                )
                .body[0]
                .body[0],
            ),
            {},
        ),
        (
            (
                ast.parse(
                    "def _f(x):\n    try:\n        y = int(x)\n    except (TypeError, ValueError):\n        y = 0\n    else:\n        y = y + 1\n    finally:\n        pass\n    for i in range(2):\n        y = y + i\n    else:\n        y = y * 2\n    while y > 100:\n        y = y - 1\n    return y"
                ).body[0],
            ),
            {},
        ),
    ],
)
def test__dataflow_candidates_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert _dataflow_candidates(*args) == expected
