"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_generate_state_mutants."""

import ast

import pytest

from Wesker.engine import _generate_state_mutants


@pytest.mark.detective
def test__generate_state_mutants_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _generate_state_mutants(
        func_node=ast.parse("def _f():\n    pass").body[0],
        max_per_category=1,
        greedy=True,
        pass_index=2,
    )
    assert result == []
