"""Auto-generated by Detective — warrant-classed tests for Wesker/filter.py::filter_categories."""

import ast

import pytest

from Wesker.filter import filter_categories


@pytest.mark.detective
def test_filter_categories_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = filter_categories(
        func_node=ast.parse("def _f():\n    pass").body[0], is_pure=True
    )
    assert result == set()
