"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::callable_origin."""

import pytest

from Wesker.ci import callable_origin


@pytest.mark.detective
def test_callable_origin_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = callable_origin(1)
    assert result is None
